name: "publish"
on:
  push:
    branches:
      - 'release-**'

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]
        # platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    # - name: install dependencies (ubuntu only)
    #   if: matrix.platform == 'ubuntu-latest'
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

    # - name: install dependencies (macos)
    #   if: matrix.platform == 'macos-latest'
    #   run: |
    #     rustup target add x86_64-apple-darwin

    - name: install app dependencies and build it
      run: yarn && yarn build
      env:
        CI: false

    - uses: tauri-apps/tauri-action@dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CI: false
      with:
        tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "v__VERSION__"
        releaseBody: "See the assets to download this version and install."
        releaseDraft: true
        prerelease: false
        includeDebug: false
