name: "test-frontend"
on:
    pull_request:
        paths:
            - "src/**"
            - "package.json"
            - "tsconfig.json"
            - "vite.config.ts"
            - "biome.json"
            - "package-lock.json"

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: npm
            - run: npm ci
            - run: npm run lint

    typecheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: npm
            - run: npm ci
            - run: npm run typecheck

    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: npm
            - run: npm ci
            - run: npm run format:check

    test:
        needs: [format, typecheck, lint]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: npm
            - run: npm ci
            - run: npm test

    build:
        needs: [test]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: npm
            - run: npm ci
            - run: npm run build
