name: "test"
on:
    pull_request:
        paths:
            - "src-tauri/**"
            - "crates/**"

jobs:
    test-libexpression:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: 1.92
            - working-directory: crates/libexpression
              run: cargo test

    test-libsphere:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: 1.92
            - working-directory: crates/libsphere
              run: cargo test

    test-mbtiles:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: 1.92
            - working-directory: crates/mbtiles
              run: cargo test

    test-tilejson:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: 1.92
            - working-directory: crates/tilejson
              run: cargo test

    test-tauri:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                  toolchain: 1.92
            - name: install system dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
            - name: create dummy dist
              run: mkdir -p dist
            - working-directory: src-tauri
              run: cargo test
